extends SceneTree

# Load every critical runtime, editor, validator, smoke test and resource
# entrypoint directly so CI catches failures that bulk import may only log.
const TARGETS := [
	"res://default_bus_layout.tres",
	"res://src/app.gd",
	"res://src/game_runtime.gd",
	"res://src/combat_runtime.gd",
	"res://src/combat_director_runtime.gd",
	"res://src/companion_runtime.gd",
	"res://src/inventory_runtime.gd",
	"res://src/story_runtime.gd",
	"res://src/save_runtime.gd",
	"res://src/equipment_runtime.gd",
	"res://src/merchant_runtime.gd",
	"res://src/arsenal_runtime.gd",
	"res://src/boss_runtime.gd",
	"res://src/cinematic_runtime.gd",
	"res://src/presentation_runtime_current.gd",
	"res://src/presentation_overlay.gd",
	"res://src/presentation_overlay_canvas.gd",
	"res://src/presentation_camera.gd",
	"res://src/sprite_animation_overlay.gd",
	"res://src/sprite_animation_overlay_current.gd",
	"res://src/sprite_animation_polish_overlay.gd",
	"res://src/adventure_feedback_overlay.gd",
	"res://src/environment_animation_overlay.gd",
	"res://src/combat_readability_overlay.gd",
	"res://src/audio_mood_controller.gd",
	"res://src/audio_mood_runtime.gd",
	"res://src/content/combat_director_validator.gd",
	"res://src/content/companion_validator.gd",
	"res://src/content/item_catalog.gd",
	"res://src/content/item_validator.gd",
	"res://src/content/story_catalog.gd",
	"res://src/content/story_validator.gd",
	"res://src/content/save_profile.gd",
	"res://src/content/save_profile_store.gd",
	"res://src/content/save_validator.gd",
	"res://src/content/equipment_catalog.gd",
	"res://src/content/equipment_validator.gd",
	"res://src/content/economy_catalog.gd",
	"res://src/content/economy_validator.gd",
	"res://src/content/arsenal_catalog.gd",
	"res://src/content/arsenal_validator.gd",
	"res://src/content/boss_catalog.gd",
	"res://src/content/boss_validator.gd",
	"res://src/content/cinematic_catalog.gd",
	"res://src/content/cinematic_validator.gd",
	"res://src/content/campaign_package.gd",
	"res://src/content/campaign_install_service.gd",
	"res://src/content/package_release_validator.gd",
	"res://src/content/campaign_audit.gd",
	"res://src/content/temporal_shift_audit.gd",
	"res://src/content/progression_recipe_audit.gd",
	"res://src/content/progression_source_index.gd",
	"res://src/content/progression_source_audit.gd",
	"res://src/content/progression_affordability_audit.gd",
	"res://src/content/presentation_catalog.gd",
	"res://src/content/presentation_validator.gd",
	"res://src/content/audio_mood_catalog.gd",
	"res://src/content/audio_mood_validator.gd",
	"res://src/content/sprite_animation_catalog.gd",
	"res://src/content/sprite_animation_validator.gd",
	"res://src/content/sprite_animation_strict_validator.gd",
	"res://src/game/encounter_zone_model.gd",
	"res://src/game/companion_model.gd",
	"res://src/game/inventory_model.gd",
	"res://src/game/story_model.gd",
	"res://src/game/equipment_model.gd",
	"res://src/game/economy_model.gd",
	"res://src/game/projectile_model.gd",
	"res://src/game/runtime_scene_contract.gd",
	"res://addons/epochbound_editor_common/editor_plugin_icon.gd",
	"res://addons/epochbound_campaign_studio/campaign_studio.gd",
	"res://addons/epochbound_campaign_studio/world_builder_studio.gd",
	"res://addons/epochbound_campaign_studio/campaign_studio_current.gd",
	"res://addons/epochbound_campaign_studio/campaign_studio_animation_current.gd",
	"res://addons/epochbound_campaign_studio/plugin.gd",
	"res://addons/epochbound_encounter_studio/encounter_canvas.gd",
	"res://addons/epochbound_encounter_studio/encounter_studio.gd",
	"res://addons/epochbound_encounter_studio/encounter_studio_controller.gd",
	"res://addons/epochbound_encounter_studio/plugin.gd",
	"res://addons/epochbound_combat_director/combat_director_canvas.gd",
	"res://addons/epochbound_combat_director/combat_director_studio.gd",
	"res://addons/epochbound_combat_director/plugin.gd",
	"res://addons/epochbound_companion_studio/companion_canvas.gd",
	"res://addons/epochbound_companion_studio/companion_studio.gd",
	"res://addons/epochbound_companion_studio/plugin.gd",
	"res://addons/epochbound_item_forge/item_forge_studio.gd",
	"res://addons/epochbound_item_forge/plugin.gd",
	"res://addons/epochbound_story_studio/story_studio.gd",
	"res://addons/epochbound_story_studio/plugin.gd",
	"res://addons/epochbound_save_state_studio/save_state_studio.gd",
	"res://addons/epochbound_save_state_studio/plugin.gd",
	"res://addons/epochbound_loadout_studio/loadout_studio.gd",
	"res://addons/epochbound_loadout_studio/plugin.gd",
	"res://addons/epochbound_trade_studio/trade_studio.gd",
	"res://addons/epochbound_trade_studio/plugin.gd",
	"res://addons/epochbound_arsenal_studio/arsenal_studio.gd",
	"res://addons/epochbound_arsenal_studio/plugin.gd",
	"res://addons/epochbound_boss_studio/boss_studio.gd",
	"res://addons/epochbound_boss_studio/plugin.gd",
	"res://addons/epochbound_cinematic_studio/cinematic_studio.gd",
	"res://addons/epochbound_cinematic_studio/plugin.gd",
	"res://addons/epochbound_package_studio/package_studio.gd",
	"res://addons/epochbound_package_studio/package_studio_current.gd",
	"res://addons/epochbound_package_studio/plugin.gd",
	"res://addons/epochbound_campaign_audit/campaign_audit_studio.gd",
	"res://addons/epochbound_campaign_audit/plugin.gd",
	"res://addons/epochbound_presentation_studio/presentation_studio.gd",
	"res://addons/epochbound_presentation_studio/plugin.gd",
	"res://addons/epochbound_audio_mood_studio/audio_mood_studio.gd",
	"res://addons/epochbound_audio_mood_studio/plugin.gd",
	"res://addons/epochbound_sprite_animation_studio/sprite_animation_studio.gd",
	"res://addons/epochbound_sprite_animation_studio/sprite_animation_studio_current.gd",
	"res://addons/epochbound_sprite_animation_studio/plugin.gd",
	"res://tools/headless_runtime_cleanup.gd",
	"res://tools/reference_journey_driver.gd",
	"res://tools/smoke_canonical_journey.gd",
	"res://tools/smoke_long_form_progression.gd",
	"res://tools/validate_content.gd",
	"res://tools/audit_campaigns.gd",
	"res://tools/smoke_runtime_scene_contract.gd",
	"res://tools/smoke_editor_plugin_icons.gd",
	"res://tools/smoke_world_model.gd",
	"res://tools/smoke_encounters.gd",
	"res://tools/smoke_combat_director.gd",
	"res://tools/smoke_companion_director.gd",
	"res://tools/smoke_item_forge.gd",
	"res://tools/smoke_item_forge_editor.gd",
	"res://tools/smoke_item_validation_edges.gd",
	"res://tools/smoke_story_studio.gd",
	"res://tools/smoke_story_studio_editor.gd",
	"res://tools/smoke_story_validation_edges.gd",
	"res://tools/smoke_save_profiles.gd",
	"res://tools/smoke_save_migrations.gd",
	"res://tools/smoke_save_state_studio.gd",
	"res://tools/smoke_loadout_runtime.gd",
	"res://tools/smoke_loadout_studio.gd",
	"res://tools/smoke_equipment_validation_edges.gd",
	"res://tools/smoke_economy_runtime.gd",
	"res://tools/smoke_trade_studio.gd",
	"res://tools/smoke_economy_validation_edges.gd",
	"res://tools/smoke_arsenal_runtime.gd",
	"res://tools/smoke_arsenal_studio.gd",
	"res://tools/smoke_arsenal_validation_edges.gd",
	"res://tools/smoke_boss_runtime.gd",
	"res://tools/smoke_boss_studio.gd",
	"res://tools/smoke_boss_validation_edges.gd",
	"res://tools/smoke_cinematic_runtime.gd",
	"res://tools/smoke_cinematic_studio.gd",
	"res://tools/smoke_cinematic_validation_edges.gd",
	"res://tools/smoke_campaign_packages.gd",
	"res://tools/smoke_package_studio.gd",
	"res://tools/smoke_package_validation_edges.gd",
	"res://tools/smoke_package_current_validation.gd",
	"res://tools/smoke_campaign_audit.gd",
	"res://tools/smoke_temporal_shift_audit.gd",
	"res://tools/smoke_campaign_audit_studio.gd",
	"res://tools/smoke_campaign_audit_edges.gd",
	"res://tools/smoke_progression_affordability.gd",
	"res://tools/smoke_presentation_runtime.gd",
	"res://tools/smoke_presentation_studio.gd",
	"res://tools/smoke_presentation_validation_edges.gd",
	"res://tools/smoke_audio_mood_runtime.gd",
	"res://tools/smoke_boss_music_stems.gd",
	"res://tools/smoke_audio_mood_studio.gd",
	"res://tools/smoke_audio_mood_validation_edges.gd",
	"res://tools/smoke_audio_campaign_scaffold.gd",
	"res://tools/smoke_sprite_animation_runtime.gd",
	"res://tools/smoke_environment_animation.gd",
	"res://tools/smoke_combat_readability_overlay.gd",
	"res://tools/smoke_sprite_animation_studio.gd",
	"res://tools/smoke_sprite_animation_validation_edges.gd",
	"res://tools/smoke_sprite_campaign_scaffold.gd",
	"res://tools/smoke_sprite_package_validation.gd",
	"res://src/app.tscn"
]

var failures: Array[String] = []


func _initialize() -> void:
	for path in TARGETS:
		var resource := ResourceLoader.load(path, "", ResourceLoader.CACHE_MODE_IGNORE)
		if resource == null:
			failures.append("Could not load or compile %s." % path)
			continue
		if path.ends_with(".gd") and not resource is GDScript:
			failures.append("Expected a GDScript resource at %s." % path)
		elif path.ends_with(".tscn") and not resource is PackedScene:
			failures.append("Expected a PackedScene resource at %s." % path)
	if failures.is_empty():
		print("Compile probe passed: canonical runtime composition, all seventeen editors, validators, smoke tests and critical resources load cleanly.")
		quit(0)
		return
	for failure in failures:
		push_error(failure)
	quit(1)
